language: python
python:
- 2.7

before_install:
- deactivate
- sudo add-apt-repository -y -r ppa:ubuntugis/ppa
- sudo apt-get update -qq
- sudo apt-get install postgresql-9.1-postgis
- sudo apt-get install postgis

install:
- virtualenv env
- source env/bin/activate
- python setup.py develop
- sudo service postgresql restart
- sudo -u postgres createuser www-data --no-superuser --no-createdb --no-createrole
- sudo -u postgres createdb -O www-data osmtm
- sudo -u postgres psql -d osmtm -c "CREATE EXTENSION postgis;"
- sudo -u postgres createdb -O www-data osmtm_tests
- sudo -u postgres psql -d osmtm_tests -c "CREATE EXTENSION postgis;"
- easy_install flake8

script:
- source env/bin/activate
- nosetests
- flake8 osmtm --exclude=osmtm/static

after_success:
- pip install coveralls
- coveralls
