language: python
python:
- 2.7

before_install:
- deactivate
- sudo add-apt-repository -y -r ppa:ubuntugis/ppa
- sudo apt-add-repository --yes ppa:mapnik/v2.2.0
- sudo apt-get update -qq
- sudo apt-get install postgresql-9.1-postgis
- sudo apt-get install postgis
- sudo apt-get install -y libmapnik mapnik-utils python-mapnik

install:
- virtualenv env
# add symbolic link for mapnik since it cannot be installed in virtualenv
- ln -s $(python -c 'import mapnik, os.path; print(os.path.dirname(mapnik.__file__))') ./env/lib/python2.7/site-packages
- source env/bin/activate
- python setup.py develop
- sudo service postgresql restart
- sudo su postgres -c "createdb template_postgis"
- echo "SELECT VERSION();" | sudo su postgres -c "psql template_postgis"
- sudo su postgres -c "psql -f /usr/share/postgresql/9.1/contrib/postgis-2.1/postgis.sql template_postgis"
- sudo su postgres -c "psql -f /usr/share/postgresql/9.1/contrib/postgis-2.1/spatial_ref_sys.sql template_postgis"
- sudo su postgres -c "echo 'SELECT POSTGIS_FULL_VERSION();' | psql template_postgis"
- sudo -u postgres createuser www-data --no-superuser --no-createdb --no-createrole
- sudo -u postgres sh osmtm/scripts/create_db.sh


script:
- source env/bin/activate
- env/bin/nosetests

after_success:
- pip install coveralls
- coveralls
